# Testing different utilities 
## Testing Adam Theta optimizer

In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
from adam_theta import AdamTheta

In [3]:
NUM_VARS = 10
theta = nn.Parameter(torch.zeros(NUM_VARS, NUM_VARS))
optim = AdamTheta(theta, lr=2e-2)

In [4]:
theta.grad = torch.ones_like(theta.data)

In [5]:
mask = torch.zeros_like(theta)
mask[1,:] = 1
mask[:,1] = 1

In [6]:
optim.step(mask)

In [7]:
theta

Parameter containing:
tensor([[ 0.0000, -0.0200,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [-0.0200, -0.0200, -0.0200, -0.0200, -0.0200, -0.0200, -0.0200, -0.0200,
         -0.0200, -0.0200],
        [ 0.0000, -0.0200,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.0000, -0.0200,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.0000, -0.0200,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.0000, -0.0200,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.0000, -0.0200,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.0000, -0.0200,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.0000, -0.0200,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000

In [8]:
optim.param_step

tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
optim.param_momentum

tensor([[0.0000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000,
         0.1000],
        [0.0000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])

In [10]:
optim.param_2nd_momentum

tensor([[0.0000, 0.0010, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010,
         0.0010],
        [0.0000, 0.0010, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0010, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0010, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0010, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0010, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0010, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0010, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0010, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])

## Test logging

In [11]:
from utils import update_stats, get_final_stats

In [17]:
torch.manual_seed(42)
vals = torch.randn(5, 2, 2)
vals[0] = 0.
vals[4] = 0.
print("Mean", torch.mean(vals[1:-1], dim=0))
print("Var", torch.var(vals[1:-1], dim=0))

Mean tensor([[-0.2113,  0.1445],
        [ 0.0186,  0.9273]])
Var tensor([[0.3106, 0.7867],
        [0.4735, 0.5212]])


In [18]:
stats_dict = {}
for i in range(vals.shape[0]):
    update_stats(stats_dict, vals[i])
    print("Stats dict at iter %i:\n" % (i+1) + str(stats_dict))
final_metrics = get_final_stats(stats_dict)
print("Final metrics")
print("Mean:", final_metrics[...,0])
print("Var:", final_metrics[...,1])
print("Min:", final_metrics[...,2])
print("Max:", final_metrics[...,3])

Stats dict at iter 1:
{'mean': tensor([[0., 0.],
        [0., 0.]]), 'var': tensor([[0., 0.],
        [0., 0.]]), 'max': tensor([[-9.0000e+15, -9.0000e+15],
        [-9.0000e+15, -9.0000e+15]]), 'min': tensor([[9.0000e+15, 9.0000e+15],
        [9.0000e+15, 9.0000e+15]]), 'count': tensor([[0., 0.],
        [0., 0.]])}
Stats dict at iter 2:
{'mean': tensor([[-0.7581,  1.0783],
        [ 0.8008,  1.6806]]), 'var': tensor([[0., 0.],
        [0., 0.]]), 'max': tensor([[-0.7581,  1.0783],
        [ 0.8008,  1.6806]]), 'min': tensor([[-0.7581,  1.0783],
        [ 0.8008,  1.6806]]), 'count': tensor([[1., 1.],
        [1., 1.]])}
Stats dict at iter 3:
{'mean': tensor([[-0.2011,  0.1958],
        [ 0.1537,  0.9611]]), 'var': tensor([[0.6205, 1.5575],
        [0.8374, 1.0356]]), 'max': tensor([[0.3559, 1.0783],
        [0.8008, 1.6806]]), 'min': tensor([[-0.7581, -0.6866],
        [-0.4934,  0.2415]]), 'count': tensor([[2., 2.],
        [2., 2.]])}
Stats dict at iter 4:
{'mean': tensor([[-0.2113